// Icon vocabulary: every icon is an SF Symbol on iOS and a Material Symbol on Android (one family per
// platform). Names are checked at compile time by expo-symbols' types.
import type { RoomKind } from '@turnproof/shared';
import type { SymbolViewProps } from 'expo-symbols';

export type SfName = Extract<SymbolViewProps['name'], string>;
export type MdName = NonNullable<Exclude<SymbolViewProps['name'], string>['android']>;
export type IconName = { sf: SfName; md: MdName };

export const icons = {
  today: { sf: 'calendar.badge.clock', md: 'event' },
  properties: { sf: 'house.fill', md: 'home' },
  history: { sf: 'clock.arrow.circlepath', md: 'history' },
  settings: { sf: 'gearshape.fill', md: 'settings' },
  camera: { sf: 'camera.fill', md: 'photo_camera' },
  addPhoto: { sf: 'camera', md: 'add_a_photo' },
  flip: { sf: 'arrow.triangle.2.circlepath.camera', md: 'cameraswitch' },
  flashOff: { sf: 'bolt.slash.fill', md: 'flash_off' },
  flashOn: { sf: 'bolt.fill', md: 'flash_on' },
  flashAuto: { sf: 'bolt.badge.automatic.fill', md: 'flash_auto' },
  library: { sf: 'photo.on.rectangle', md: 'photo_library' },
  photo: { sf: 'photo', md: 'image' },
  check: { sf: 'checkmark', md: 'check' },
  checkCircle: { sf: 'checkmark.circle.fill', md: 'check_circle' },
  issue: { sf: 'exclamationmark.triangle.fill', md: 'warning' },
  location: { sf: 'location.fill', md: 'location_on' },
  locationOff: { sf: 'location.slash', md: 'location_off' },
  verified: { sf: 'checkmark.seal.fill', md: 'verified' },
  add: { sf: 'plus', md: 'add' },
  minus: { sf: 'minus', md: 'remove' },
  close: { sf: 'xmark', md: 'close' },
  chevronForward: { sf: 'chevron.right', md: 'chevron_right' },
  chevronBack: { sf: 'chevron.left', md: 'chevron_left' },
  chevronDown: { sf: 'chevron.down', md: 'expand_more' },
  chevronUp: { sf: 'chevron.up', md: 'expand_less' },
  arrowUp: { sf: 'arrow.up', md: 'arrow_upward' },
  arrowDown: { sf: 'arrow.down', md: 'arrow_downward' },
  more: { sf: 'ellipsis.circle', md: 'more_vert' },
  share: { sf: 'square.and.arrow.up', md: 'share' },
  link: { sf: 'link', md: 'link' },
  linkOff: { sf: 'link.badge.plus', md: 'link_off' },
  open: { sf: 'safari', md: 'open_in_new' },
  pdf: { sf: 'doc.richtext', md: 'picture_as_pdf' },
  csv: { sf: 'tablecells', md: 'table_view' },
  trash: { sf: 'trash', md: 'delete' },
  edit: { sf: 'pencil', md: 'edit' },
  clock: { sf: 'clock', md: 'schedule' },
  timer: { sf: 'timer', md: 'timer' },
  key: { sf: 'key', md: 'key' },
  account: { sf: 'person.crop.circle', md: 'account_circle' },
  people: { sf: 'person.2.fill', md: 'group' },
  personAdd: { sf: 'person.badge.plus', md: 'person_add' },
  bell: { sf: 'bell.badge', md: 'notifications_active' },
  bellOff: { sf: 'bell.slash', md: 'notifications_off' },
  upload: { sf: 'icloud.and.arrow.up', md: 'cloud_upload' },
  uploadOff: { sf: 'icloud.slash', md: 'cloud_off' },
  logout: { sf: 'rectangle.portrait.and.arrow.right', md: 'logout' },
  info: { sf: 'info.circle', md: 'info' },
  shield: { sf: 'lock.shield', md: 'shield' },
  doc: { sf: 'doc.text', md: 'description' },
  help: { sf: 'questionmark.circle', md: 'help' },
  database: { sf: 'externaldrive.badge.exclamationmark', md: 'database' },
  play: { sf: 'play.fill', md: 'play_arrow' },
  finish: { sf: 'flag.checkered', md: 'sports_score' },
  sparkles: { sf: 'sparkles', md: 'cleaning_services' },
  appearance: { sf: 'circle.lefthalf.filled', md: 'contrast' },
  pin: { sf: 'mappin.and.ellipse', md: 'pin_drop' },
  note: { sf: 'note.text', md: 'sticky_note_2' },
  refresh: { sf: 'arrow.clockwise', md: 'refresh' },
  calendar: { sf: 'calendar', md: 'calendar_month' },
  supplies: { sf: 'basket', md: 'shopping_basket' },
  door: { sf: 'door.left.hand.open', md: 'door_front' },
  rooms: { sf: 'square.grid.2x2', md: 'grid_view' },
  code: { sf: 'number', md: 'tag' },
  role: { sf: 'person.text.rectangle', md: 'badge' },
  dev: { sf: 'hammer', md: 'build' },
} as const satisfies Record<string, IconName>;

export const roomIcons: Record<RoomKind, IconName> = {
  bedroom: { sf: 'bed.double.fill', md: 'bed' },
  bathroom: { sf: 'bathtub.fill', md: 'bathtub' },
  kitchen: { sf: 'fork.knife', md: 'kitchen' },
  living: { sf: 'sofa.fill', md: 'weekend' },
  entry: { sf: 'door.left.hand.closed', md: 'door_front' },
  outdoor: { sf: 'leaf.fill', md: 'yard' },
  laundry: { sf: 'washer.fill', md: 'local_laundry_service' },
  other: { sf: 'square.dashed', md: 'meeting_room' },
};
